<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST" Id="{05bea583-3305-4137-8317-3c4e75dfa876}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	suite_Example : Example;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="PRG_TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>